### ISSUE TITLE
configure error on mac OSX

### ISSUE THREAD

**Issue by nlegoff** [alchemy-fr/Phraseanet-Indexer#2]
```
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for mysql_config... no
configure: error: mysql_config program not found
```

mysql_config program is in /opt/local/lib/mysql5/bin

**Comment by gfpl001** [comment]
same for me

**Comment by romainneutron** [comment]
Any news @jygaulier  ?

**Comment by gfpl001** [comment]
yes first solved i have installed :  libmysqlclient-dev ;)

**Comment by jygaulier** [comment]
This may be due to a missing path in $PATH. On 'some' installs of MySQL (for ex. MacPorts which install under /opt/local... ), the path may not be set.
One solution is to install MySQL AND MySQL-Dev under STANDARD path "/usr/local...", for ex. using "homebrew" package manager.
Another solution is to locate your mysql binaries, check you can run "mysql_config" and do "$PATH=path_to_mysql_bin:$PATH" before runing the scripts.

Anyway don't forget that you will need the DEVELOPMENT files of MySQL to build, and as found by @gfpl001, installing those files can solve the issue.
